services:
  app:
    build: .
    container_name: ithive_container
    restart: always
    env_file:
      - env_file.env
    environment:
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_FLYWAY_LOCATIONS: classpath:db/migration
      SERVER_PORT: 8089

    volumes:
      - .:/app
      - ./pom.xml:/app/pom.xml
    ports:
      - "8089:8089"
    depends_on:
      - db

  db:
    image: postgres
    container_name: postgres_db
    env_file:
      - env_file.env
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data  # This volume persists the database data

volumes:
  db-data: